import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Proyek Prapemrosesan Data: World Bank Global Education Statistics (EdStats)\n",
                "**Mata Kuliah:** Rekayasa Data (Data Engineering)\n",
                "**Sumber Dataset:** [Kaggle - World Bank Education Statistics](https://www.kaggle.com/datasets/theworldbank/education-statistics) | [World Bank Official Data Catalog](https://datacatalog.worldbank.org/search/dataset/0038480/Education-Statistics)  \n",
                "**Topik:** Pipeline Data Preprocessing Lengkap 5 Tabel dan Benchmarking Angka Partisipasi Murni (*Net Enrolment Rate*) Pendidikan Dasar Negara Anggota G20 (2000–2017)\n",
                "---\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Langkah 1: Impor Pustaka, Pemuatan 5 Berkas Data, dan Profiling Awal\n",
                "Memuat pustaka analisis data (`pandas`, `numpy`, `scipy`, `sklearn`, `matplotlib`, `seaborn`), membaca 5 tabel dataset Bank Dunia (`EdStatsData`, `EdStatsCountry`, `EdStatsSeries`, `EdStatsFootNote`, `EdStatsCountry-Series`), dan memeriksa profil dimensi data mentah."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "from scipy import stats\n",
                "from sklearn.decomposition import PCA\n",
                "from sklearn.preprocessing import StandardScaler\n",
                "\n",
                "pd.set_option('display.max_columns', 50)\n",
                "pd.set_option('display.float_format', lambda x: '%.2f' % x)\n",
                "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
                "plt.rcParams['font.sans-serif'] = 'DejaVu Sans'\n",
                "\n",
                "# Pemetaan indikator pendidikan dasar\n",
                "IND_NAMES = {\n",
                "    'SE.PRM.NENR': 'Partisipasi Murni Total (%)',\n",
                "    'SE.PRM.NENR.FE': 'Partisipasi Murni Perempuan (%)',\n",
                "    'SE.PRM.NENR.MA': 'Partisipasi Murni Laki-laki (%)',\n",
                "    'SE.PRM.CMPT.ZS': 'Kelulusan Pendidikan Dasar (%)',\n",
                "    'SE.PRM.ENRL.TC.ZS': 'Rasio Murid per Guru',\n",
                "    'SE.PRM.DROP.ZS': 'Tingkat Putus Sekolah (%)'\n",
                "}\n",
                "\n",
                "print('Pustaka siap. Versi Pandas:', pd.__version__)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "DATA_DIR = './edstats-csv-zip-32-mb-'\n",
                "\n",
                "# Pemuatan 5 tabel dataset\n",
                "df_data = pd.read_csv(os.path.join(DATA_DIR, 'EdStatsData.csv'))\n",
                "df_country = pd.read_csv(os.path.join(DATA_DIR, 'EdStatsCountry.csv'))\n",
                "df_series = pd.read_csv(os.path.join(DATA_DIR, 'EdStatsSeries.csv'))\n",
                "df_footnote = pd.read_csv(os.path.join(DATA_DIR, 'EdStatsFootNote.csv'))\n",
                "df_country_series = pd.read_csv(os.path.join(DATA_DIR, 'EdStatsCountry-Series.csv'))\n",
                "\n",
                "print('--- Profil Dimensi 5 Tabel ---')\n",
                "print(f'1. EdStatsData (Tabel Fakta Utama)       : {df_data.shape[0]:,} baris x {df_data.shape[1]} kolom')\n",
                "print(f'2. EdStatsCountry (Dimensi Negara)        : {df_country.shape[0]:,} baris x {df_country.shape[1]} kolom')\n",
                "print(f'3. EdStatsSeries (Dimensi Indikator)      : {df_series.shape[0]:,} baris x {df_series.shape[1]} kolom')\n",
                "print(f'4. EdStatsFootNote (Log Metadata Survei)  : {df_footnote.shape[0]:,} baris x {df_footnote.shape[1]} kolom')\n",
                "print(f'5. EdStatsCountry-Series (Asosiasi Lokal) : {df_country_series.shape[0]:,} baris x {df_country_series.shape[1]} kolom')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Evaluasi missing values pada tabel fakta utama\n",
                "total_cells = df_data.shape[0] * df_data.shape[1]\n",
                "total_missing = df_data.isnull().sum().sum()\n",
                "print('--- Evaluasi Kualitas Data Mentah ---')\n",
                "print(f'Total Sel              : {total_cells:,} sel')\n",
                "print(f'Total Sel Kosong (NaN) : {total_missing:,} sel')\n",
                "print(f'Missing Rate           : {(total_missing / total_cells) * 100:.2f}%')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Langkah 2: Strategi Reduksi Data Awal (Data Reduction)\n",
                "Menerapkan seleksi dimensi geografis (19 Negara Berdaulat Anggota G20), seleksi fitur domain pendidikan dasar berbasis Partisipasi Murni (*Net Enrolment Rate / NER*), dan reduksi dimensi temporal kontinu (2000–2017) untuk mengeliminasi kolom proyeksi teoritis masa depan (>2017) dan artefak `Unnamed: 69`."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Reduksi geografis: 19 Negara Anggota G20\n",
                "g20_countries = [\n",
                "    'ARG', 'AUS', 'BRA', 'CAN', 'CHN', 'FRA', 'DEU', 'IND', 'IDN', 'ITA',\n",
                "    'JPN', 'KOR', 'MEX', 'RUS', 'SAU', 'ZAF', 'TUR', 'GBR', 'USA'\n",
                "]\n",
                "df_reduced = df_data[df_data['Country Code'].isin(g20_countries)].copy()\n",
                "\n",
                "# 2. Seleksi indikator pendidikan dasar\n",
                "key_indicators = list(IND_NAMES.keys())\n",
                "df_reduced = df_reduced[df_reduced['Indicator Code'].isin(key_indicators)].copy()\n",
                "\n",
                "# 3. Reduksi rentang tahun (2000 - 2017)\n",
                "year_cols = [str(y) for y in range(2000, 2018)]\n",
                "id_cols = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code']\n",
                "df_reduced = df_reduced[id_cols + year_cols].copy()\n",
                "\n",
                "print('=== EVALUASI EFISIENSI REDUKSI DATA ===')\n",
                "print(f'Dimensi Awal    : {df_data.shape[0]:,} baris x {df_data.shape[1]} kolom')\n",
                "print(f'Dimensi Akhir   : {df_reduced.shape[0]:,} baris x {df_reduced.shape[1]} kolom')\n",
                "print(f'Pengurangan Baris: {(1 - df_reduced.shape[0]/df_data.shape[0])*100:.2f}%')\n",
                "print(f'Pengurangan Kolom: {(1 - df_reduced.shape[1]/df_data.shape[1])*100:.2f}%')\n",
                "\n",
                "mem_before = df_data.memory_usage(deep=True).sum() / (1024 * 1024)\n",
                "mem_after = df_reduced.memory_usage(deep=True).sum() / (1024 * 1024)\n",
                "print(f'Alokasi Memori  : {mem_before:.2f} MB -> {mem_after:.2f} MB')\n",
                "\n",
                "# Sampel data tereduksi\n",
                "sample_preview = df_reduced[df_reduced['Country Code'].isin(['IDN', 'USA', 'JPN']) & (df_reduced['Indicator Code'] == 'SE.PRM.NENR')]\n",
                "display(sample_preview[['Country Name', 'Country Code', 'Indicator Name', '2000', '2005', '2010', '2015']])"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Langkah 3: Integrasi 5 Tabel & Resolusi Konflik Skema/Representasi Nilai (Data Integration)\n",
                "Menggabungkan tabel fakta dengan 4 tabel dimensi (`EdStatsCountry`, `EdStatsSeries`, `EdStatsFootNote`, `EdStatsCountry-Series`), mengatasi **konflik skema** (penamaan kunci berbeda) dan **konflik representasi data** (konversi `YR2000` ke integer `2000`), serta melakukan **Uji Chi-Square $\\chi^2$** untuk deteksi redundansi."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Integrasi dimensi negara (EdStatsCountry)\n",
                "country_cols = ['Country Code', 'Region', 'Income Group', 'Lending category']\n",
                "df_integrated = pd.merge(\n",
                "    df_reduced,\n",
                "    df_country[country_cols],\n",
                "    on='Country Code',\n",
                "    how='left',\n",
                "    validate='m:1'\n",
                ")\n",
                "\n",
                "# 2. Integrasi dimensi indikator (EdStatsSeries)\n",
                "df_integrated = pd.merge(\n",
                "    df_integrated,\n",
                "    df_series[['Series Code', 'Topic', 'Unit of measure']],\n",
                "    left_on='Indicator Code',\n",
                "    right_on='Series Code',\n",
                "    how='left',\n",
                "    validate='m:1'\n",
                ").drop(columns=['Series Code'])\n",
                "\n",
                "# 3. Restrukturisasi format long\n",
                "meta_cols = ['Country Code', 'Country Name', 'Region', 'Income Group', 'Lending category', 'Indicator Code', 'Topic']\n",
                "df_long = pd.melt(df_integrated, id_vars=meta_cols, value_vars=year_cols, var_name='Year', value_name='Value')\n",
                "df_long['Year'] = df_long['Year'].astype(int)\n",
                "\n",
                "# 4. Integrasi log metadata survei (EdStatsFootNote) & pembersihan format tahun\n",
                "df_fn_clean = df_footnote.dropna(subset=['CountryCode', 'SeriesCode', 'Year']).copy()\n",
                "df_fn_clean['Year_Clean'] = df_fn_clean['Year'].astype(str).str.replace('YR', '', regex=False)\n",
                "df_fn_clean = df_fn_clean[df_fn_clean['Year_Clean'].str.isnumeric()]\n",
                "df_fn_clean['Year'] = df_fn_clean['Year_Clean'].astype(int)\n",
                "\n",
                "# Ekstraksi atribut provenance\n",
                "df_fn_g20 = df_fn_clean[df_fn_clean['CountryCode'].isin(g20_countries) & df_fn_clean['SeriesCode'].isin(key_indicators) & df_fn_clean['Year'].isin(range(2000, 2018))].copy()\n",
                "df_fn_g20['Is_Estimated'] = df_fn_g20['DESCRIPTION'].str.contains('estimat|uis', case=False, na=False)\n",
                "\n",
                "df_long_fn = pd.merge(\n",
                "    df_long,\n",
                "    df_fn_g20[['CountryCode', 'SeriesCode', 'Year', 'Is_Estimated']].drop_duplicates(),\n",
                "    left_on=['Country Code', 'Indicator Code', 'Year'],\n",
                "    right_on=['CountryCode', 'SeriesCode', 'Year'],\n",
                "    how='left'\n",
                ").drop(columns=['CountryCode', 'SeriesCode'])\n",
                "df_long_fn['Is_Estimated'] = df_long_fn['Is_Estimated'].fillna(False)\n",
                "\n",
                "# 5. Integrasi catatan negara-indikator (EdStatsCountry-Series)\n",
                "df_cs_clean = df_country_series.dropna(subset=['CountryCode', 'SeriesCode']).copy()\n",
                "df_cs_clean['Has_Country_Series_Note'] = True\n",
                "df_long_all = pd.merge(\n",
                "    df_long_fn,\n",
                "    df_cs_clean[['CountryCode', 'SeriesCode', 'Has_Country_Series_Note']].drop_duplicates(),\n",
                "    left_on=['Country Code', 'Indicator Code'],\n",
                "    right_on=['CountryCode', 'SeriesCode'],\n",
                "    how='left'\n",
                ").drop(columns=['CountryCode', 'SeriesCode'])\n",
                "df_long_all['Has_Country_Series_Note'] = df_long_all['Has_Country_Series_Note'].fillna(False)\n",
                "\n",
                "print('=== HASIL INTEGRASI 5 TABEL ===')\n",
                "print(f'Total Baris Terintegrasi: {df_long_all.shape[0]:,} baris')\n",
                "print('\\nSebaran Status Estimasi (Is_Estimated):')\n",
                "print(df_long_all['Is_Estimated'].value_counts())\n",
                "\n",
                "# Sampel integrasi 2015\n",
                "sample_int = df_long_all[df_long_all['Country Code'].isin(['IDN', 'USA', 'DEU', 'IND']) & (df_long_all['Year'] == 2015) & (df_long_all['Indicator Code'] == 'SE.PRM.NENR')]\n",
                "display(sample_int[['Country Name', 'Year', 'Region', 'Income Group', 'Indicator Code', 'Value', 'Is_Estimated']])"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Uji Chi-Square untuk dependensi Income Group vs Region\n",
                "contingency_tbl = pd.crosstab(df_integrated['Income Group'], df_integrated['Region'])\n",
                "chi2_stat, p_val, dof, expected = stats.chi2_contingency(contingency_tbl)\n",
                "\n",
                "print('=== ANALISIS REDUNDANSI (CHI-SQUARE TEST) ===')\n",
                "print(f'Chi-Square Statistic (χ²): {chi2_stat:.4f}')\n",
                "print(f'Degrees of Freedom (df)  : {dof}')\n",
                "print(f'p-value                  : {p_val:.4e}')\n",
                "if p_val < 0.05:\n",
                "    print('Kesimpulan: Terdapat asosiasi dependensi signifikan antara Income Group dan Region (p < 0.05).')\n",
                "display(contingency_tbl)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Langkah 4: Pembersihan Data (Data Cleaning) & Transformasi Tidy Panel\n",
                "Melakukan pivoting ke format panel fitur (*Country-Year*), imputasi bertingkat 3-Tier (*interpolasi temporal, median kelompok pendapatan, median global*), deteksi outlier via IQR & Boxplot, serta ekspor dataset bersih."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Pivoting ke format panel (19 Negara x 18 Tahun = 342 Baris)\n",
                "df_panel = df_long_all.pivot(\n",
                "    index=['Country Code', 'Country Name', 'Region', 'Income Group', 'Lending category', 'Year'],\n",
                "    columns='Indicator Code',\n",
                "    values='Value'\n",
                ").reset_index()\n",
                "df_panel.columns.name = None\n",
                "\n",
                "print('Dimensi Format Panel Sebelum Imputasi:', df_panel.shape)\n",
                "print('\\nMissing Values Sebelum Imputasi:')\n",
                "missing_summary = df_panel[key_indicators].isnull().sum().rename(index=IND_NAMES)\n",
                "print(missing_summary)\n",
                "missing_panel_raw_rate = (df_panel[key_indicators].isnull().sum().sum() / (df_panel.shape[0] * len(key_indicators))) * 100\n",
                "print(f'\\nMissing Rate Panel Sebelum Imputasi: {missing_panel_raw_rate:.2f}%')\n",
                "\n",
                "# 2. Imputasi bertingkat (3-Tier Imputation)\n",
                "df_clean = df_panel.sort_values(by=['Country Code', 'Year']).copy()\n",
                "\n",
                "# Tingkat 1: Interpolasi linier temporal per negara\n",
                "for ind in key_indicators:\n",
                "    df_clean[ind] = df_clean.groupby('Country Code')[ind].transform(\n",
                "        lambda g: g.interpolate(method='linear', limit_direction='both')\n",
                "    )\n",
                "\n",
                "# Tingkat 2: Median per kelompok pendapatan (Income Group)\n",
                "for ind in key_indicators:\n",
                "    df_clean[ind] = df_clean.groupby('Income Group')[ind].transform(\n",
                "        lambda g: g.fillna(g.median())\n",
                "    )\n",
                "\n",
                "# Tingkat 3: Median global G20 (fallback)\n",
                "for ind in key_indicators:\n",
                "    df_clean[ind] = df_clean[ind].fillna(df_clean[ind].median())\n",
                "\n",
                "print('\\nMissing Values Setelah Imputasi (Lengkap 100%):')\n",
                "print(df_clean[key_indicators].isnull().sum().rename(index=IND_NAMES))\n",
                "print(f'\\nJumlah Baris Duplikat: {df_clean.duplicated().sum()}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Deteksi Outlier & Boxplot Sebaran Indikator\n",
                "plt.figure(figsize=(14, 5))\n",
                "df_clean_renamed = df_clean.rename(columns=IND_NAMES)\n",
                "ind_indonesian_cols = list(IND_NAMES.values())\n",
                "\n",
                "df_melted_ind = pd.melt(df_clean_renamed, id_vars=['Country Name', 'Year'], value_vars=ind_indonesian_cols, var_name='Indikator', value_name='Nilai')\n",
                "\n",
                "sns.boxplot(data=df_melted_ind, x='Indikator', y='Nilai', palette='Set2')\n",
                "plt.title('Deteksi Outlier & Sebaran Indikator Pendidikan Dasar Negara G20', fontsize=13, fontweight='bold')\n",
                "plt.xticks(rotation=15, ha='right', fontsize=10)\n",
                "plt.ylabel('Nilai Indikator (% / Rasio)', fontsize=11)\n",
                "plt.tight_layout()\n",
                "plt.savefig('boxplot_outlier_detection.png', dpi=300)\n",
                "plt.show()\n",
                "\n",
                "print('=== STATISTIK DESKRIPTIF DATASET BERSIH ===')\n",
                "display(df_clean_renamed[ind_indonesian_cols].describe().round(2))\n",
                "\n",
                "# Ekspor dataset bersih ke CSV\n",
                "OUTPUT_CSV = 'EdStats_Cleaned_G20_2000_2017.csv'\n",
                "df_clean.to_csv(OUTPUT_CSV, index=False)\n",
                "print(f'\\nDataset bersih diekspor ke: {OUTPUT_CSV}')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Langkah 5: Analisis Kovariansi, Korelasi Pearson, & Reduksi Dimensi dengan PCA\n",
                "Menerapkan konsep dari slide materi *P05 Data Preprocessing*: Memetakan matriks korelasi/kovariansi fitur, melakukan standarisasi Z-Score ($Z = \\frac{X - \\mu}{\\sigma}$), menghitung *Eigenvalues* & *Eigenvectors*, serta mereduksi 6 dimensi indikator menjadi 2 komponen utama (*Principal Components*) dengan visualisasi sebaran (*PCA 2D Projection*)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Matriks Korelasi & Kovariansi\n",
                "corr_mat = df_clean_renamed[ind_indonesian_cols].corr()\n",
                "cov_mat = df_clean_renamed[ind_indonesian_cols].cov()\n",
                "\n",
                "plt.figure(figsize=(10, 8))\n",
                "sns.heatmap(corr_mat, annot=True, cmap='coolwarm', vmin=-1, vmax=1, fmt='.2f', linewidths=0.5, annot_kws={'size': 10})\n",
                "plt.title('Matriks Korelasi Pearson Antar Indikator Pendidikan Dasar G20', fontsize=13, fontweight='bold')\n",
                "plt.xticks(rotation=20, ha='right', fontsize=10)\n",
                "plt.yticks(fontsize=10)\n",
                "plt.tight_layout()\n",
                "plt.savefig('correlation_heatmap.png', dpi=300)\n",
                "plt.show()\n",
                "\n",
                "print('Matriks Kovariansi Numerik:')\n",
                "display(cov_mat.round(2))"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Standarisasi Z-Score\n",
                "scaler = StandardScaler()\n",
                "X_scaled = scaler.fit_transform(df_clean[key_indicators])\n",
                "\n",
                "# 3. Ekstraksi 2 Komponen Utama (PCA)\n",
                "pca = PCA(n_components=2)\n",
                "X_pca = pca.fit_transform(X_scaled)\n",
                "\n",
                "df_clean['PC1'] = X_pca[:, 0]\n",
                "df_clean['PC2'] = X_pca[:, 1]\n",
                "\n",
                "evr = pca.explained_variance_ratio_\n",
                "print('=== HASIL PRINCIPAL COMPONENT ANALYSIS (PCA) ===')\n",
                "print(f'Explained Variance Ratio PC1: {evr[0]*100:.2f}%')\n",
                "print(f'Explained Variance Ratio PC2: {evr[1]*100:.2f}%')\n",
                "print(f'Total Retensi Variansi (2 PC): {sum(evr)*100:.2f}%')\n",
                "\n",
                "# 4. Visualisasi Proyeksi 2D PCA\n",
                "plt.figure(figsize=(11, 6.5))\n",
                "sns.scatterplot(\n",
                "    data=df_clean,\n",
                "    x='PC1',\n",
                "    y='PC2',\n",
                "    hue='Income Group',\n",
                "    style='Region',\n",
                "    s=100,\n",
                "    alpha=0.9\n",
                ")\n",
                "plt.title(f'Proyeksi 2D PCA G20 (Retensi Variansi {sum(evr)*100:.1f}%)', fontsize=13, fontweight='bold')\n",
                "plt.xlabel(f'PC1 ({evr[0]*100:.1f}% Variansi - Akses & Kelulusan)')\n",
                "plt.ylabel(f'PC2 ({evr[1]*100:.1f}% Variansi - Rasio Beban Pengajaran)')\n",
                "plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n",
                "plt.tight_layout()\n",
                "plt.savefig('pca_2d_projection.png', dpi=300)\n",
                "plt.show()\n",
                "\n",
                "# 5. Scree Plot Variansi PCA\n",
                "pca_all = PCA().fit(X_scaled)\n",
                "fig, ax1 = plt.subplots(figsize=(8.5, 4.5))\n",
                "pc_names = [f'PC{i+1}' for i in range(len(pca_all.explained_variance_ratio_))]\n",
                "indiv_var = pca_all.explained_variance_ratio_ * 100\n",
                "cum_var = np.cumsum(indiv_var)\n",
                "\n",
                "ax1.bar(pc_names, indiv_var, color='#3498db', alpha=0.85, label='Variansi Individual (%)')\n",
                "ax1.set_ylabel('Explained Variance Individual (%)', color='#2c3e50', fontsize=11)\n",
                "ax1.set_ylim(0, 100)\n",
                "\n",
                "ax2 = ax1.twinx()\n",
                "ax2.plot(pc_names, cum_var, color='#e74c3c', marker='o', linewidth=2.5, label='Variansi Kumulatif (%)')\n",
                "ax2.set_ylabel('Explained Variance Kumulatif (%)', color='#e74c3c', fontsize=11)\n",
                "ax2.set_ylim(0, 110)\n",
                "ax2.axhline(80, color='gray', linestyle='--', alpha=0.7, label='Threshold 80%')\n",
                "\n",
                "for i, txt in enumerate(cum_var):\n",
                "    ax2.annotate(f'{txt:.1f}%', (pc_names[i], txt + 2.5), ha='center', fontsize=9, fontweight='bold', color='#c0392b')\n",
                "\n",
                "plt.title('Scree Plot PCA: Retensi Variansi Komponen Utama (G20)', fontsize=12, fontweight='bold')\n",
                "plt.tight_layout()\n",
                "plt.savefig('pca_scree_plot.png', dpi=300)\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 6. Langkah 6: Diskretisasi Data & Transformasi Konsep Hierarki\n",
                "Menerapkan teknik diskretisasi berbasis *Interval Binning* pada dua indikator kunci: **Kelulusan Pendidikan Dasar** (`<96%`, `96-99%`, `>99%`) dan **Rasio Murid per Guru** (`<15`, `15-20`, `>20`) untuk membentuk konsep hierarki kategorikal yang komprehensif."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Diskretisasi Tingkat Kelulusan Pendidikan Dasar\n",
                "labels_kelulusan = ['Kelulusan Rendah (<96%)', 'Kelulusan Sedang (96-99%)', 'Kelulusan Tinggi (>99%)']\n",
                "df_clean['Kategori_Kelulusan'] = pd.cut(df_clean['SE.PRM.CMPT.ZS'], bins=[0, 96, 99, 150], labels=labels_kelulusan)\n",
                "\n",
                "# 2. Diskretisasi Rasio Murid per Guru\n",
                "labels_guru = ['Rasio Ideal (<15)', 'Rasio Moderat (15-20)', 'Rasio Padat (>20)']\n",
                "df_clean['Kategori_Rasio_Guru'] = pd.cut(df_clean['SE.PRM.ENRL.TC.ZS'], bins=[0, 15, 20, 100], labels=labels_guru)\n",
                "\n",
                "print('=== DISTRIBUSI KATEGORI KELULUSAN PENDIDIKAN DASAR ===')\n",
                "print(df_clean['Kategori_Kelulusan'].value_counts())\n",
                "print('\\n=== DISTRIBUSI KATEGORI RASIO MURID PER GURU ===')\n",
                "print(df_clean['Kategori_Rasio_Guru'].value_counts())\n",
                "\n",
                "# Sampel perbandingan kategori (Tahun 2015)\n",
                "benchmark_sample = df_clean[\n",
                "    (df_clean['Country Code'].isin(['IDN', 'USA', 'JPN', 'DEU', 'IND', 'BRA', 'GBR', 'CHN'])) & \n",
                "    (df_clean['Year'] == 2015)\n",
                "].rename(columns=IND_NAMES)\n",
                "\n",
                "display(benchmark_sample[['Country Name', 'Year', 'Income Group', 'Partisipasi Murni Total (%)', 'Kelulusan Pendidikan Dasar (%)', 'Kategori_Kelulusan', 'Rasio Murid per Guru', 'Kategori_Rasio_Guru']])"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 7. Langkah 7: Visualisasi Hasil Prapemrosesan & Analisis Tren\n",
                "Bagian ini dibagi menjadi dua fokus analitis utama:\n",
                "1. **Evaluasi Kualitas Sebelum vs. Sesudah Prapemrosesan (*Before vs. After Evaluation*)**: Memvalidasi penurunan missing values, efisiensi memori, dan studi kasus rekonstruksi data deret waktu.\n",
                "2. **Analisis Tren & Wawasan Kebijakan Pendidikan G20 (*Trends & Insights*)**: Memetakan dinamika 19 negara G20, peta panas makro, dan paritas gender."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 7.1 EVALUASI SEBELUM VS. SESUDAH PRAPEMROSESAN\n",
                "\n",
                "# 1. Perbandingan Missing Rate 3 Tahap & Efisiensi Ukuran Berkas\n",
                "fig, ax = plt.subplots(1, 2, figsize=(13, 5))\n",
                "stages = ['Data Mentah\\n(EdStatsData)', 'Panel G20\\n(Sebelum Imputasi)', 'Panel G20\\n(Setelah Imputasi)']\n",
                "missing_rates = [(total_missing / total_cells) * 100, missing_panel_raw_rate, 0.0]\n",
                "colors = ['#d9534f', '#f0ad4e', '#5cb85c']\n",
                "\n",
                "ax[0].bar(stages, missing_rates, color=colors, width=0.55)\n",
                "ax[0].set_ylabel('Missing Rate (%)', fontsize=11)\n",
                "ax[0].set_title('Progres Penurunan Missing Rate (3 Tahap)', fontweight='bold')\n",
                "ax[0].set_ylim(0, 100)\n",
                "for p in ax[0].patches:\n",
                "    ax[0].annotate(f'{p.get_height():.2f}%', (p.get_x() + p.get_width() / 2., p.get_height() + 2), ha='center', fontweight='bold')\n",
                "\n",
                "ax[1].bar(['Data Mentah (Disk)', 'Data Bersih G20 (Disk)'], [326.4, os.path.getsize(OUTPUT_CSV)/1024], color=['#f0ad4e', '#0275d8'])\n",
                "ax[1].set_ylabel('Ukuran Berkas (MB / KB)', fontsize=11)\n",
                "ax[1].set_title(f'Efisiensi Penyimpanan: 326.4 MB -> {os.path.getsize(OUTPUT_CSV)/1024:.1f} KB', fontweight='bold')\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.savefig('before_after_comparison.png', dpi=300)\n",
                "plt.show()\n",
                "\n",
                "# 2. Studi Kasus Imputasi Deret Waktu: Indonesia (Ujung Gap) & India (Tengah Gap)\n",
                "fig, axes = plt.subplots(2, 2, figsize=(14, 8.5), sharex=True)\n",
                "years = list(range(2000, 2018))\n",
                "\n",
                "# Studi Kasus: Indonesia\n",
                "idn_raw = df_panel[df_panel['Country Code'] == 'IDN'].sort_values('Year')['SE.PRM.NENR'].values\n",
                "idn_clean = df_clean[df_clean['Country Code'] == 'IDN'].sort_values('Year')['SE.PRM.NENR'].values\n",
                "mask_idn = np.isnan(idn_raw)\n",
                "years_idn_miss = np.array(years)[mask_idn]\n",
                "\n",
                "axes[0, 0].plot(years, idn_raw, marker='o', color='#e74c3c', linewidth=2, label='Observasi Asli')\n",
                "axes[0, 0].scatter(years_idn_miss, [90.0]*len(years_idn_miss), marker='x', color='black', s=90, linewidth=2, label='Tahun Kosong', zorder=5)\n",
                "axes[0, 0].set_title('A1. Indonesia Mentah (Gap di Ujung Periode: 2000-2001, 2016-2017)', fontweight='bold', fontsize=11)\n",
                "axes[0, 0].set_ylabel('Partisipasi Murni (%)', fontsize=10)\n",
                "axes[0, 0].set_ylim(87, 95.5)\n",
                "axes[0, 0].legend(loc='lower right', fontsize=9)\n",
                "axes[0, 0].grid(True, linestyle='--', alpha=0.5)\n",
                "\n",
                "axes[0, 1].plot(years, idn_clean, marker='o', color='#27ae60', linewidth=2.5, label='Kurva Panel Kontinu')\n",
                "axes[0, 1].scatter(years_idn_miss, idn_clean[mask_idn], marker='D', color='#f39c12', s=80, label='Hasil Imputasi 3-Tier', zorder=5)\n",
                "axes[0, 1].set_title('A2. Indonesia Bersih (Setelah Imputasi 3-Tier)', fontweight='bold', fontsize=11)\n",
                "axes[0, 1].set_ylim(87, 95.5)\n",
                "axes[0, 1].legend(loc='lower right', fontsize=9)\n",
                "axes[0, 1].grid(True, linestyle='--', alpha=0.5)\n",
                "\n",
                "# Studi Kasus: India\n",
                "ind_raw = df_panel[df_panel['Country Code'] == 'IND'].sort_values('Year')['SE.PRM.NENR'].values\n",
                "ind_clean = df_clean[df_clean['Country Code'] == 'IND'].sort_values('Year')['SE.PRM.NENR'].values\n",
                "mask_ind = np.isnan(ind_raw)\n",
                "years_ind_miss = np.array(years)[mask_ind]\n",
                "\n",
                "axes[1, 0].plot(years, ind_raw, marker='o', color='#e74c3c', linewidth=2, label='Observasi Asli')\n",
                "axes[1, 0].scatter(years_ind_miss, [88.0]*len(years_ind_miss), marker='x', color='black', s=90, linewidth=2, label='Tahun Kosong', zorder=5)\n",
                "axes[1, 0].set_title('B1. India Mentah (Gap di Tengah Periode: 2004-2006)', fontweight='bold', fontsize=11)\n",
                "axes[1, 0].set_xlabel('Tahun', fontsize=10)\n",
                "axes[1, 0].set_ylabel('Partisipasi Murni (%)', fontsize=10)\n",
                "axes[1, 0].set_ylim(78, 95)\n",
                "axes[1, 0].legend(loc='lower right', fontsize=9)\n",
                "axes[1, 0].grid(True, linestyle='--', alpha=0.5)\n",
                "\n",
                "axes[1, 1].plot(years, ind_clean, marker='o', color='#2980b9', linewidth=2.5, label='Kurva Panel Kontinu')\n",
                "axes[1, 1].scatter(years_ind_miss, ind_clean[mask_ind], marker='D', color='#f39c12', s=80, label='Hasil Interpolasi Linier', zorder=5)\n",
                "axes[1, 1].set_title('B2. India Bersih (Setelah Interpolasi Linier)', fontweight='bold', fontsize=11)\n",
                "axes[1, 1].set_xlabel('Tahun', fontsize=10)\n",
                "axes[1, 1].set_ylim(78, 95)\n",
                "axes[1, 1].legend(loc='lower right', fontsize=9)\n",
                "axes[1, 1].grid(True, linestyle='--', alpha=0.5)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.savefig('before_after_imputation_case_study.png', dpi=300)\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 7.2 ANALISIS TREN LONGITUDINAL & WAWASAN PENDIDIKAN G20\n",
                "\n",
                "# 3. Tren Partisipasi Murni (NER) 19 Negara G20 (2000–2017)\n",
                "plt.figure(figsize=(14, 7.5))\n",
                "sns.lineplot(\n",
                "    data=df_clean,\n",
                "    x='Year',\n",
                "    y='SE.PRM.NENR',\n",
                "    hue='Country Name',\n",
                "    palette='tab20',\n",
                "    marker='o',\n",
                "    linewidth=1.8,\n",
                "    alpha=0.9\n",
                ")\n",
                "plt.title('Tren Angka Partisipasi Murni (NER) 19 Negara Anggota G20 (2000–2017)', fontsize=13, fontweight='bold')\n",
                "plt.xlabel('Tahun', fontsize=11)\n",
                "plt.ylabel('Angka Partisipasi Murni / NER (%)', fontsize=11)\n",
                "plt.ylim(80, 102)\n",
                "plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left', ncol=2, fontsize=9)\n",
                "plt.tight_layout()\n",
                "plt.savefig('visualisasi_tren_pendidikan_g20.png', dpi=300)\n",
                "plt.show()\n",
                "\n",
                "# 4. Heatmap Temporal Partisipasi Murni 19 Negara G20\n",
                "plt.figure(figsize=(13, 8))\n",
                "heatmap_matrix = df_clean.pivot(index='Country Name', columns='Year', values='SE.PRM.NENR')\n",
                "sns.heatmap(\n",
                "    heatmap_matrix,\n",
                "    cmap='YlGnBu',\n",
                "    annot=True,\n",
                "    fmt='.1f',\n",
                "    cbar_kws={'label': 'Partisipasi Murni (%)'},\n",
                "    linewidths=0.5\n",
                ")\n",
                "plt.title('Peta Panas (Heatmap) Evolusi Partisipasi Murni 19 Negara G20 (2000–2017)', fontsize=13, fontweight='bold')\n",
                "plt.xlabel('Tahun', fontsize=11)\n",
                "plt.ylabel('Negara Anggota G20', fontsize=11)\n",
                "plt.tight_layout()\n",
                "plt.savefig('temporal_heatmap_g20.png', dpi=300)\n",
                "plt.show()\n",
                "\n",
                "# 5. Plot Paritas Gender G20\n",
                "plt.figure(figsize=(8.5, 6.5))\n",
                "sns.scatterplot(\n",
                "    data=df_clean,\n",
                "    x='SE.PRM.NENR.MA',\n",
                "    y='SE.PRM.NENR.FE',\n",
                "    hue='Income Group',\n",
                "    style='Region',\n",
                "    s=80,\n",
                "    alpha=0.85\n",
                ")\n",
                "plt.plot([78, 101], [78, 101], color='#e74c3c', linestyle='--', linewidth=1.8, label='Paritas Gender 1:1 (y = x)')\n",
                "plt.title('Analisis Paritas Gender Partisipasi Pendidikan Dasar di G20 (2000–2017)', fontsize=12, fontweight='bold')\n",
                "plt.xlabel('Partisipasi Murni Siswa Laki-laki (%)', fontsize=11)\n",
                "plt.ylabel('Partisipasi Murni Siswa Perempuan (%)', fontsize=11)\n",
                "plt.xlim(78, 101)\n",
                "plt.ylim(78, 101)\n",
                "plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')\n",
                "plt.tight_layout()\n",
                "plt.savefig('gender_parity_analysis.png', dpi=300)\n",
                "plt.show()"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbformat": 4,
            "nbformat_minor": 2
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open('preprocessing_edstats.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print('Notebook preprocessing_edstats.ipynb successfully generated!')
